version: '3.1'

services:

  jenkins:
    build: .
    restart: always
    volumes:
        - jenkins_home:/var/jenkins_home
    ports:
        - 8090:8080
        - 50000:50000

volumes:
    jenkins_home:
